openapi: 3.0.1
info:
  description: API for CD4PE V1
  license:
    name: Apache 2.0
    url: https://puppet.com
  title: CD4PE API V1
  version: "1.0"
externalDocs:
  url: https://puppet.com/docs
servers:
- description: server 1
  url: /api/v1
security:
- default: []
paths:
  /workspaces/{workspaceId}/controlrepos:
    get:
      description: Returns a list of Control Repos
      operationId: getControlRepos
      parameters:
      - explode: false
        in: path
        name: workspaceId
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ControlRepo'
          description: A list of control repos
        400:
          description: Invalid ID supplied
  /auth/token:
    post:
      operationId: createToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTokenRequest'
      responses:
        default:
          content:
            text/plain:
              schema:
                type: string
          description: An API token
        400:
          description: Invalid credentials provided
      summary: Create a token associated with the passed in credentials
  /user:
    get:
      operationId: getUserInfo
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUserDetails'
          description: The user
        400:
          description: Invalid ID supplied
      summary: Get information about the user associated with this token
  /permitted:
    post:
      operationId: evaluatePermissions
      parameters:
      - explode: true
        in: query
        name: workspaceId
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluatePermissionsRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permitted'
          description: Permitted response
        400:
          description: Invalid credentials provided
      summary: Evaluate permissions for a user
  /internal/workspaces/{workspaceId}/integrations/pe:
    get:
      description: List PE integrations with tokens for a workspace. This is a internal
        only api.
      operationId: listPeIntegrationsWithToken
      parameters:
      - description: Identifies a workspace
        explode: false
        in: path
        name: workspaceId
        required: true
        schema:
          $ref: '#/components/schemas/WorkspaceId'
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPEIntegrationsWithTokenResponse'
          description: List PE integrations with Token response
        400:
          description: Invalid workspace id supplied
        404:
          description: workspace not found
      summary: List PE integrations for a workspace
components:
  parameters:
    WorkspaceIdInPath:
      description: Identifies a workspace
      explode: false
      in: path
      name: workspaceId
      required: true
      schema:
        $ref: '#/components/schemas/WorkspaceId'
      style: simple
  responses:
    ListPEIntegrationsWithTokenResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListPEIntegrationsWithTokenResponse'
      description: List PE integrations with Token response
    PermittedResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Permitted'
      description: Permitted response
  schemas:
    ContainerBuildConfiguration:
      properties:
        buildCapabilities:
          items:
            type: string
          type: array
        buildVars:
          items:
            type: string
          type: array
        dockerFilePath:
          type: string
        noDind:
          type: boolean
        serverDomain:
          type: string
        vmArgs:
          items:
            type: string
          type: array
        vmImage:
          type: string
        vmProvider:
          enum:
          - DockerHub
          - ECR
          - Private
          - GCR
          - PublicDockerHub
          type: string
        vmPull:
          type: boolean
        noDind_asStr:
          type: string
          writeOnly: true
        vmPull_asStr:
          type: string
          writeOnly: true
      type: object
    ControlRepo:
      properties:
        created:
          format: int64
          type: integer
        description:
          type: string
        displayName:
          type: string
        domain:
          type: string
        lastCommitId:
          type: string
        lastDeploy:
          $ref: '#/components/schemas/RollingDeploymentEvent'
        lastImpactAnalysis:
          $ref: '#/components/schemas/PEImpactAnalysisEvent'
        lastDeployment:
          $ref: '#/components/schemas/DeploymentAppEvent'
        lastJob:
          $ref: '#/components/schemas/VmJobInstanceEvent'
        name:
          type: string
        srcRepoDisplayName:
          type: string
        srcRepoDisplayOwner:
          type: string
        srcRepoId:
          type: string
        srcRepoName:
          type: string
        srcRepoOwner:
          type: string
        srcRepoProvider:
          enum:
          - BITBUCKET
          - BITBUCKETSERVER
          - GITHUB
          - GITHUBENTERPRISE
          - GITLAB
          - AZUREDEVOPS
          type: string
        repository:
          $ref: '#/components/schemas/Repository'
      type: object
    ControlRepoId:
      properties:
        domain:
          type: string
        name:
          type: string
      type: object
    CreateTokenRequest:
      example:
        password: password
        email: email
      properties:
        email:
          type: string
        password:
          type: string
      type: object
    DeploymentAppEvent:
      properties:
        appName:
          type: string
        containerName:
          type: string
        domain:
          type: string
        eventId:
          format: int64
          type: integer
        eventName:
          type: string
        eventTime:
          format: int64
          type: integer
        eventType:
          enum:
          - COMMIT
          - BUILD
          - RELEASE
          - DEPLOY
          - DOCKERIMAGE
          - PUSH
          - PULLREQUEST
          - VMJOB
          - ROLLINGDEPLOY
          - PEIMPACTANALYSIS
          - PEMODULEDEPLOYMENT
          - DEPLOYMENT
          type: string
        maxChildEventId:
          format: int64
          type: integer
        parentEventId:
          format: int64
          type: integer
        userAccountId:
          type: string
        username:
          type: string
        authorName:
          type: string
        authorUsername:
          type: string
        branch:
          type: string
        commitId:
          type: string
        commitMsg:
          type: string
        commitUrl:
          type: string
        pullRequestDestBranch:
          type: string
        pullRequestHtmlUrl:
          type: string
        pullRequestId:
          type: string
        pullRequestNumber:
          type: string
        pullRequestSourceBranch:
          type: string
        repoId:
          type: string
        repoName:
          type: string
        repoOwner:
          type: string
        repoProvider:
          type: string
        repoType:
          type: string
        repoUrl:
          type: string
        webhookEventId:
          type: string
        artifactId:
          type: string
        artifactShortId:
          type: string
        buildId:
          type: string
        buildNum:
          format: int64
          type: integer
        customReleaseVersion:
          type: string
        releaseVersion:
          type: string
        controlRepoName:
          type: string
        deploymentDescription:
          type: string
        deploymentEndTime:
          format: int64
          type: integer
        deploymentId:
          format: int64
          type: integer
        deploymentStartTime:
          format: int64
          type: integer
        deploymentState:
          enum:
          - WAITING
          - QUEUED
          - CANCELLED
          - RUNNING
          - DONE
          - FAILED
          - ABORTED
          - TIMEDOUT
          - PENDING_APPROVAL
          - APPROVED
          - DECLINED
          type: string
        deploymentPlanName:
          type: string
        isAutoDeploy:
          type: boolean
        nodeGroupId:
          type: string
        nodeGroupName:
          type: string
        puppetEnterpriseServerName:
          type: string
        sha:
          type: string
        sourceBranch:
          type: string
        targetBranch:
          type: string
        buildNum_asStr:
          type: string
          writeOnly: true
        eventTime_asStr:
          type: string
          writeOnly: true
        eventId_asStr:
          type: string
          writeOnly: true
        maxChildEventId_asStr:
          type: string
          writeOnly: true
        parentEventId_asStr:
          type: string
          writeOnly: true
      type: object
    PEImpactAnalysisEnvironment:
      properties:
        deploymentType:
          enum:
          - DIRECT_MERGE
          - TEMPORARY_BRANCH
          - INCREMENTAL_BRANCH
          - BLUE_GREEN_BRANCH
          - CODE_ONLY_DEPLOY
          - FEATURE_BRANCH
          type: string
        moduleImpactAnalysisControlRepoId:
          $ref: '#/components/schemas/ControlRepoId'
        nodeGroupId:
          type: string
        peCredentialsId:
          $ref: '#/components/schemas/PuppetEnterpriseCredentialsId'
        pipelineDestinationId:
          type: string
      type: object
    PEImpactAnalysisEvent:
      properties:
        appName:
          type: string
        containerName:
          type: string
        domain:
          type: string
        eventId:
          format: int64
          type: integer
        eventName:
          type: string
        eventTime:
          format: int64
          type: integer
        eventType:
          enum:
          - COMMIT
          - BUILD
          - RELEASE
          - DEPLOY
          - DOCKERIMAGE
          - PUSH
          - PULLREQUEST
          - VMJOB
          - ROLLINGDEPLOY
          - PEIMPACTANALYSIS
          - PEMODULEDEPLOYMENT
          - DEPLOYMENT
          type: string
        maxChildEventId:
          format: int64
          type: integer
        parentEventId:
          format: int64
          type: integer
        userAccountId:
          type: string
        username:
          type: string
        authorName:
          type: string
        authorUsername:
          type: string
        branch:
          type: string
        commitId:
          type: string
        commitMsg:
          type: string
        commitUrl:
          type: string
        pullRequestDestBranch:
          type: string
        pullRequestHtmlUrl:
          type: string
        pullRequestId:
          type: string
        pullRequestNumber:
          type: string
        pullRequestSourceBranch:
          type: string
        repoId:
          type: string
        repoName:
          type: string
        repoOwner:
          type: string
        repoProvider:
          type: string
        repoType:
          type: string
        repoUrl:
          type: string
        webhookEventId:
          type: string
        artifactId:
          type: string
        artifactShortId:
          type: string
        buildId:
          type: string
        buildNum:
          format: int64
          type: integer
        customReleaseVersion:
          type: string
        releaseVersion:
          type: string
        controlRepoName:
          type: string
        endTime:
          format: int64
          type: integer
        environments:
          items:
            $ref: '#/components/schemas/PEImpactAnalysisEnvironment'
          type: array
        impactAnalysisId:
          format: int64
          type: integer
        isAutoDeploy:
          type: boolean
        moduleName:
          type: string
        sha:
          type: string
        sourceBranch:
          type: string
        startTime:
          format: int64
          type: integer
        state:
          enum:
          - WAITING
          - QUEUED
          - CANCELLED
          - RUNNING
          - DONE
          - FAILED
          - ABORTED
          - TIMEDOUT
          - PENDING_APPROVAL
          - APPROVED
          - DECLINED
          type: string
        endTime_asStr:
          type: string
          writeOnly: true
        isAutoDeploy_asStr:
          type: string
          writeOnly: true
        startTime_asStr:
          type: string
          writeOnly: true
        impactAnalysisId_asStr:
          type: string
          writeOnly: true
        buildNum_asStr:
          type: string
          writeOnly: true
        eventTime_asStr:
          type: string
          writeOnly: true
        eventId_asStr:
          type: string
          writeOnly: true
        maxChildEventId_asStr:
          type: string
          writeOnly: true
        parentEventId_asStr:
          type: string
          writeOnly: true
      type: object
    PuppetEnterpriseCredentialsId:
      properties:
        domain:
          type: string
        name:
          type: string
      type: object
    Repository:
      properties:
        displayName:
          type: string
        displayOwner:
          type: string
        name:
          type: string
        owner:
          type: string
        project:
          type: string
        provider:
          enum:
          - BITBUCKET
          - BITBUCKETSERVER
          - GITHUB
          - GITHUBENTERPRISE
          - GITLAB
          - AZUREDEVOPS
          type: string
        repositoryId:
          type: string
        webhookId:
          type: string
      type: object
    RollingDeploymentEvent:
      properties:
        appName:
          type: string
        containerName:
          type: string
        domain:
          type: string
        eventId:
          format: int64
          type: integer
        eventName:
          type: string
        eventTime:
          format: int64
          type: integer
        eventType:
          enum:
          - COMMIT
          - BUILD
          - RELEASE
          - DEPLOY
          - DOCKERIMAGE
          - PUSH
          - PULLREQUEST
          - VMJOB
          - ROLLINGDEPLOY
          - PEIMPACTANALYSIS
          - PEMODULEDEPLOYMENT
          - DEPLOYMENT
          type: string
        maxChildEventId:
          format: int64
          type: integer
        parentEventId:
          format: int64
          type: integer
        userAccountId:
          type: string
        username:
          type: string
        authorName:
          type: string
        authorUsername:
          type: string
        branch:
          type: string
        commitId:
          type: string
        commitMsg:
          type: string
        commitUrl:
          type: string
        pullRequestDestBranch:
          type: string
        pullRequestHtmlUrl:
          type: string
        pullRequestId:
          type: string
        pullRequestNumber:
          type: string
        pullRequestSourceBranch:
          type: string
        repoId:
          type: string
        repoName:
          type: string
        repoOwner:
          type: string
        repoProvider:
          type: string
        repoType:
          type: string
        repoUrl:
          type: string
        webhookEventId:
          type: string
        artifactId:
          type: string
        artifactShortId:
          type: string
        buildId:
          type: string
        buildNum:
          format: int64
          type: integer
        customReleaseVersion:
          type: string
        releaseVersion:
          type: string
        controlRepoName:
          type: string
        deploymentDescription:
          type: string
        deploymentEndTime:
          format: int64
          type: integer
        deploymentId:
          format: int64
          type: integer
        deploymentStartTime:
          format: int64
          type: integer
        deploymentState:
          enum:
          - WAITING
          - QUEUED
          - CANCELLED
          - RUNNING
          - DONE
          - FAILED
          - ABORTED
          - TIMEDOUT
          - PENDING_APPROVAL
          - APPROVED
          - DECLINED
          type: string
        deploymentType:
          enum:
          - DIRECT_MERGE
          - TEMPORARY_BRANCH
          - INCREMENTAL_BRANCH
          - BLUE_GREEN_BRANCH
          - CODE_ONLY_DEPLOY
          - FEATURE_BRANCH
          type: string
        isAutoDeploy:
          type: boolean
        nodeGrouId:
          type: string
        nodeGroupName:
          type: string
        puppetEnterpriseServerName:
          type: string
        sha:
          type: string
        sourceBranch:
          type: string
        targetBranch:
          type: string
        isAutoDeploy_asStr:
          type: string
          writeOnly: true
        deploymentId_asStr:
          type: string
          writeOnly: true
        deploymentStartTime_asStr:
          type: string
          writeOnly: true
        deploymentEndTime_asStr:
          type: string
          writeOnly: true
        buildNum_asStr:
          type: string
          writeOnly: true
        eventTime_asStr:
          type: string
          writeOnly: true
        eventId_asStr:
          type: string
          writeOnly: true
        maxChildEventId_asStr:
          type: string
          writeOnly: true
        parentEventId_asStr:
          type: string
          writeOnly: true
      type: object
    VmJobInstanceEvent:
      properties:
        appName:
          type: string
        containerName:
          type: string
        domain:
          type: string
        eventId:
          format: int64
          type: integer
        eventName:
          type: string
        eventTime:
          format: int64
          type: integer
        eventType:
          enum:
          - COMMIT
          - BUILD
          - RELEASE
          - DEPLOY
          - DOCKERIMAGE
          - PUSH
          - PULLREQUEST
          - VMJOB
          - ROLLINGDEPLOY
          - PEIMPACTANALYSIS
          - PEMODULEDEPLOYMENT
          - DEPLOYMENT
          type: string
        maxChildEventId:
          format: int64
          type: integer
        parentEventId:
          format: int64
          type: integer
        userAccountId:
          type: string
        username:
          type: string
        authorName:
          type: string
        authorUsername:
          type: string
        branch:
          type: string
        commitId:
          type: string
        commitMsg:
          type: string
        commitUrl:
          type: string
        pullRequestDestBranch:
          type: string
        pullRequestHtmlUrl:
          type: string
        pullRequestId:
          type: string
        pullRequestNumber:
          type: string
        pullRequestSourceBranch:
          type: string
        repoId:
          type: string
        repoName:
          type: string
        repoOwner:
          type: string
        repoProvider:
          type: string
        repoType:
          type: string
        repoUrl:
          type: string
        webhookEventId:
          type: string
        artifactId:
          type: string
        artifactShortId:
          type: string
        buildId:
          type: string
        buildNum:
          format: int64
          type: integer
        customReleaseVersion:
          type: string
        releaseVersion:
          type: string
        jobConfiguration:
          $ref: '#/components/schemas/ContainerBuildConfiguration'
        jobDescription:
          type: string
        jobEndTime:
          format: int64
          type: integer
        jobName:
          type: string
        jobStartTime:
          format: int64
          type: integer
        jobStatus:
          type: string
        vmJobInstanceId:
          format: int64
          type: integer
        vmJobTemplateId:
          format: int64
          type: integer
        vmJobTemplateId_asStr:
          type: string
          writeOnly: true
        jobEndTime_asStr:
          type: string
          writeOnly: true
        jobStartTime_asStr:
          type: string
          writeOnly: true
        vmJobInstanceId_asStr:
          type: string
          writeOnly: true
        buildNum_asStr:
          type: string
          writeOnly: true
        eventTime_asStr:
          type: string
          writeOnly: true
        eventId_asStr:
          type: string
          writeOnly: true
        maxChildEventId_asStr:
          type: string
          writeOnly: true
        parentEventId_asStr:
          type: string
          writeOnly: true
      type: object
    PuppetEnterpriseCredentials:
      properties:
        certificate:
          type: string
        codeManagerEndpoint:
          type: string
        defaultBranchOverrideSupported:
          type: boolean
        domain:
          type: string
        name:
          type: string
        nodeClassifierEndpoint:
          type: string
        orchestratorEndpoint:
          type: string
        protectedEnvironmentsCount:
          format: int32
          type: integer
        puppetDbEndpoint:
          type: string
        puppetServerCertificate:
          type: string
        puppetServerEndpoint:
          type: string
        puppetServerPrivateKey:
          type: string
        token:
          type: string
        tokenExpiration:
          format: int64
          type: integer
        useLegacyCompileEndpoint:
          type: boolean
        defaultBranchOverrideSupported_asStr:
          type: string
          writeOnly: true
        protectedEnvironmentsCount_asStr:
          type: string
          writeOnly: true
        tokenExpiration_asStr:
          type: string
          writeOnly: true
        useLegacyCompileEndpoint_asStr:
          type: string
          writeOnly: true
      type: object
    User:
      example:
        firstName: firstName
        lastName: lastName
        rootUser: false
        domain: d2
        companyName: companyName
        gravatarEmail: gravatarEmail
        createdTime: 0
        id: 2
        userName: userName
        email: email
        superUser: false
      properties:
        domain:
          example: d2
          pattern: ^d\d+
          type: string
        id:
          example: 2
          format: int64
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        userName:
          minLength: 1
          type: string
        email:
          minLength: 1
          type: string
        createdTime:
          format: int64
          type: integer
        companyName:
          type: string
        gravatarEmail:
          type: string
        rootUser:
          default: false
          type: boolean
        superUser:
          default: false
          type: boolean
      type: object
    CurrentUserDetails:
      example:
        workspaces:
        - domain: domain
          name: name
        - domain: domain
          name: name
        user:
          firstName: firstName
          lastName: lastName
          rootUser: false
          domain: d2
          companyName: companyName
          gravatarEmail: gravatarEmail
          createdTime: 0
          id: 2
          userName: userName
          email: email
          superUser: false
      properties:
        user:
          $ref: '#/components/schemas/User'
        workspaces:
          items:
            $ref: '#/components/schemas/Workspace'
          type: array
      type: object
    Workspace:
      example:
        domain: domain
        name: name
      properties:
        domain:
          pattern: ^d\d+
          type: string
        name:
          minLength: 1
          type: string
      required:
      - domain
      - name
      type: object
    EvaluatePermissionsRequest:
      example:
        permissions:
        - instance: instance
          action: CREATE
          objectType: GROUP
        - instance: instance
          action: CREATE
          objectType: GROUP
        token: 0
      properties:
        token:
          format: int64
          type: integer
        permissions:
          items:
            $ref: '#/components/schemas/PermissionTriplet'
          type: array
      type: object
    Permitted:
      description: List of entries of whether user has corresponding permission
      example:
        results:
        - true
      properties:
        results:
          description: List of results for requested permissions
          example:
          - true
          items:
            type: boolean
          type: array
      required:
      - results
      title: Permitted
      type: object
    PermissionTriplet:
      example:
        instance: instance
        action: CREATE
        objectType: GROUP
      properties:
        objectType:
          enum:
          - GROUP
          - SERVER
          - PROJECT
          - SETTING
          - ENVIRONMENT
          - WORKFLOW
          - DASHBOARD
          - VM_JOB_TEMPLATE
          - MODULE
          - CONTROL_REPO
          - BOLT_PROJECT
          type: string
        action:
          enum:
          - CREATE
          - READ
          - WRITE
          - DELETE
          - ADMIN
          - BUILD
          - RUN
          - DEPLOY
          - PROMOTE
          - MANAGE
          - EDIT
          type: string
        instance:
          type: string
      required:
      - action
      - instance
      - objectType
      type: object
    PuppetEnterpriseCredentialsWithToken:
      description: Puppet Enterprise credentials with token
      example:
        protectedEnvironmentsCount: 0
        puppetServerCertificate: puppetServerCertificate
        useLegacyCompileEndpoint: true
        puppetDbEndpoint: puppetDbEndpoint
        certificate: certificate
        puppetServerPrivateKey: puppetServerPrivateKey
        orchestratorEndpoint: orchestratorEndpoint
        token: token
        puppetServerEndpoint: puppetServerEndpoint
        tokenExpiration: 6
        domain: domain
        nodeClassifierEndpoint: nodeClassifierEndpoint
        name: name
        codeManagerEndpoint: codeManagerEndpoint
      properties:
        domain:
          type: string
        name:
          type: string
        certificate:
          type: string
        codeManagerEndpoint:
          type: string
        nodeClassifierEndpoint:
          type: string
        orchestratorEndpoint:
          type: string
        puppetDbEndpoint:
          type: string
        puppetServerEndpoint:
          type: string
        puppetServerCertificate:
          type: string
        puppetServerPrivateKey:
          type: string
        useLegacyCompileEndpoint:
          type: boolean
        protectedEnvironmentsCount:
          format: int32
          type: integer
        token:
          type: string
        tokenExpiration:
          format: int64
          type: integer
      title: PuppetEnterpriseCredentialsWithToken
      type: object
    ListPEIntegrationsWithTokenResponse:
      description: List integrated PE instances
      example:
        peIntegrations:
        - protectedEnvironmentsCount: 0
          puppetServerCertificate: puppetServerCertificate
          useLegacyCompileEndpoint: true
          puppetDbEndpoint: puppetDbEndpoint
          certificate: certificate
          puppetServerPrivateKey: puppetServerPrivateKey
          orchestratorEndpoint: orchestratorEndpoint
          token: token
          puppetServerEndpoint: puppetServerEndpoint
          tokenExpiration: 6
          domain: domain
          nodeClassifierEndpoint: nodeClassifierEndpoint
          name: name
          codeManagerEndpoint: codeManagerEndpoint
        - protectedEnvironmentsCount: 0
          puppetServerCertificate: puppetServerCertificate
          useLegacyCompileEndpoint: true
          puppetDbEndpoint: puppetDbEndpoint
          certificate: certificate
          puppetServerPrivateKey: puppetServerPrivateKey
          orchestratorEndpoint: orchestratorEndpoint
          token: token
          puppetServerEndpoint: puppetServerEndpoint
          tokenExpiration: 6
          domain: domain
          nodeClassifierEndpoint: nodeClassifierEndpoint
          name: name
          codeManagerEndpoint: codeManagerEndpoint
      properties:
        peIntegrations:
          description: List of PE integrations (including the token)
          items:
            $ref: '#/components/schemas/PuppetEnterpriseCredentialsWithToken'
          type: array
      required:
      - peIntegrations
      title: ListPEIntegrationsWithTokenResponse
      type: object
    WorkspaceId:
      example: d3
      pattern: ^d\d+
      type: string
  securitySchemes:
    default:
      in: header
      name: Authorization
      type: apiKey
